# version: "3.7"
services:
  # image project
  micro01_app:
    build:
      args:
        user: milena
        uid: 1000
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - micro01_network

  # nginx
  micro01_nginx:
    image: nginx:alpine
    ports:
      - "8181:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - micro01_network

  # db mysql
  db_micro01:
    image: mysql:5.7.22
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
      MYSQL_USER: ${DB_USERNAME:-username}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3131:3306"
    networks:
      - micro01_network
networks:
  micro01_network:
    driver: bridge
